### ISSUE TITLE
Release that works with clojure.spec.alpha?

### ISSUE THREAD

**Issue by iku000888** [CoNarrative/precept#102]
I have a toy codebase that I would like to try out precept in, but because it has code that depends on clojure.spec.alpha it cannot coexist with `[precept "0.3.1-alpha"]` (dependent on the pre-split).

I understand cool features are being developed and precept is still alpha, just saying it would be really convenient for trying it out :)

**Comment by alex-dixon** [comment]
@iku000888 Sorry we are behind on our release schedule. Things should work as of 0.3.2-alpha if you would like to try cloning from master and running `lein install`, then referencing 0.3.2-alpha in your project so it will run from your local maven repo. Official release will be coming soon, probably as 0.4.0-alpha but not sure yet. :)

**Comment by iku000888** [comment]
No worries and sorry for the noise :)

(Worked around by checking it out in the mean while)
