### ISSUE TITLE
Full stack example

### ISSUE THREAD

**Issue by alex-dixon** [CoNarrative/precept#12]
We have a start on this using sente for client-server communication and Datomic for db.

Not sure what the example app should be. Full stack todo app? 😅 

A simple example could simply show persistence with Datomic. Fancier could add rules sessions on the client and the server.

**Comment by alex-dixon** [comment]
This didn't make the cut for 0.3.0-alpha due to time constrants and is now low priority until we receive interest from the community in a full stack example.

**Comment by gdeer81** [comment]
a small E-commerce app can showcase frameworks better than a todo app

**Comment by abustamam** [comment]
@gdeer81 I think that would be a fantastic example -- the amount of filters users can add to their query in an e-commerce app would definitely showcase Precept's main use case.

**Comment by gdeer81** [comment]
Who wants to help me build a fake online shoe store? Precept-o-licious Kicks.

**Comment by alex-dixon** [comment]
@gdeer81 As it turns out @abustamam and I just spoke for about an hour on plans for examples and we would like to take this one on. Sorry. 😞  We'd like to at least get the core of it up but are willing to accept PRs from there.

**Comment by gdeer81** [comment]
Awesome, good luck! I'm excited to see what you guys come up with. It will be nice to have a core reference app to build off of if and when I get two spare minutes to rub together.

**Comment by alex-dixon** [comment]
Added #89
