### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by Risto-Stevcev** [CoNarrative/precept#123]
Is this project still alive? it looks like it hasn't had any commits in a while 🙁

**Comment by alex-dixon** [comment]
It's alive and well! I believe the commit history reflects stability and our recent focus on other projects. We're planning an open source release of at least one. 

If there's anything I can help with just let me know. I can be reached here or on Clojurians Slack.

**Comment by Risto-Stevcev** [comment]
Nice! thanks for clarifying 🙂
