### ISSUE TITLE
Determine support for Datomic-style map insertions

### ISSUE THREAD

**Issue by alex-dixon** [CoNarrative/precept#28]
With Datomic, users typically create transaction data using a map syntax instead of a tuple syntax. Here's an example that uses this and makes defining entities easier with a helper function

```clj
(defn todo [title]
 {:db/id (guid) :todo/title title :todo/time-created (.now js/Date) :todo/done false})
```
Maps also allow namespace-map syntax that will be released in Clojure 1.9 and already appears in CLJS 1.9.

```clj
(ns facts
  (:require [libx.spec.todo :as todo])

(defn todo [title]
  (assoc
    #::todo{:title title :time-created (.now js/Date) :done false}
    :db/id (guid))
 ```

I think we should try support this even though it may slow down our inserts/retracts. We are already trying to parse insert arguments as vectors, vectors of vectors, tuple records, vectors of tuple  records, vectors with tuple records in 3rd position and vectors of vectors with tuple records in 3rd position.

**Comment by mikegai** [comment]
Make sure it supports nested maps a la Datomic
http://docs.datomic.com/transactions.html

**Comment by alex-dixon** [comment]
@mikegai 
I think supporting non-nested with no additional semantics is something we could support really quickly.We might have to bite off a little more in order to support that the way Datomic appears to. 
In particular, from http://docs.datomic.com/transactions.html#sec-3-5:

> Either the reference to the nested map must be a component attribute, or the nested map must include a unique attribute. This constraint prevents the accidental creation of easily-orphaned entities that have no identity or relation to other entities.

We want to support the component concept anyway just not sure if we want to do it all in the same pass. Thoughts?

**Comment by mikegai** [comment]
I'm fine with doing it incrementally - one-level deep first as syntactic sugar, then component semantics later (where it gets really powerful). Go ahead and split into separate issues - one for each.

**Comment by alex-dixon** [comment]
Closing in favor of #82, #83
