### ISSUE TITLE
Support predicate functions in value slot

### ISSUE THREAD

**Issue by alex-dixon** [CoNarrative/precept#78]
Clara supports `>` and `<` boolean operators within rule expressions:
http://www.clara-rules.org/docs/booleans

We should be able to write a LHS expression as:
```clj
 [[_ :attr (> 42 ?v)]]
```
I believe the correct expansion into Clara's DSL using our fact type function is:
```clj
[:attr (= ?v (:v this)) (> 42 (:v this))]
```
Have added failing test cases and should be able to submit a PR with a fix tomorrow.

**Comment by nrfm** [comment]
Thanks! :) I spent the morning creating  a minimal counter example to help me grasp the structure and abstractions of the framework and couldn't make those predicates work.
Where is this " fact type function"? I am finding it difficult to translate clara's syntax into precept's.

**Comment by alex-dixon** [comment]
@nrfm Just had a conversation on Discord about this, clearly we need better docs and we've been working on that. In the meantime the best I can offer is https://github.com/CoNarrative/precept/blob/master/test/clj/precept/rule_test.cljc and the conversation in the Discord channel where I tried to explain it a bit

**Comment by nrfm** [comment]
@alex-dixon i just found the Discord channel and was reading through that. cheers!

**Comment by alex-dixon** [comment]
Clara actually supports arbitrary predicates and does not privilege `>` `<` or other comparators. I have changed the title of this issue and the PR (#81) accordingly.

**Comment by alex-dixon** [comment]
Added in #81
